compressionLevel: mixed

enableGlobalCache: true

nodeLinker: node-modules

npmAuditExcludePackages:
  - angular
  # pending | high     | GHSA-4w4v-5hc9-xrr2 | angular >=1.3.0 <=1.8.3      | 1.8.3 brought in by angular-bootstrap-switch@npm:0.5.2
  # pending | moderate | GHSA-2qqx-w9hr-q5gx | angular <=1.8.3              | 1.8.3 brought in by angular-bootstrap-switch@npm:0.5.2
  # pending | moderate | GHSA-2vrf-hf26-jrp5 | angular <=1.8.3              | 1.8.3 brought in by angular-bootstrap-switch@npm:0.5.2
  # pending | moderate | GHSA-m2h2-264f-f486 | angular >=1.7.0              | 1.8.3 brought in by angular-bootstrap-switch@npm:0.5.2
  # pending | moderate | GHSA-prc3-vjfx-vhm9 | angular <=1.8.3              | 1.8.3 brought in by angular-bootstrap-switch@npm:0.5.2
  # pending | moderate | GHSA-qwqh-hm9m-p5hr | angular <=1.8.3              | 1.8.3 brought in by angular-bootstrap-switch@npm:0.5.2
  # pending | low      | GHSA-j58c-ww9w-pwp5 | angular <=1.8.3              | 1.8.3 brought in by angular-bootstrap-switch@npm:0.5.2
  # pending | low      | GHSA-m9gf-397r-hwpg | angular >=1.3.0-rc.4 <=1.8.3 | 1.8.3 brought in by angular-bootstrap-switch@npm:0.5.2
  # pending | low      | GHSA-mqm9-c95h-x2p6 | angular <=1.8.3              | 1.8.3 brought in by angular-bootstrap-switch@npm:0.5.2

yarnPath: .yarn/releases/yarn-4.11.0.cjs
