import 'angular';
import 'jquery';
import 'angular-animate';
import 'angular-sanitize';
import 'ui-router';
import 'angular-patternfly';
import 'angular-ui-sortable';
import 'angular-dragdrop';
import 'angular-bootstrap-switch';
