import 'angular';
import 'lodash';
import 'jquery';
import 'bootstrap';
import 'angular-animate';
import 'angular-sanitize';
import 'ui-router';
import 'angular-bootstrap/ui-bootstrap-tpls';
import 'bootstrap-combobox';
import 'bootstrap-datepicker';
import 'bootstrap-select';
import 'bootstrap-switch';
import 'bootstrap-treeview/src/js/bootstrap-treeview';
import 'd3';
import 'c3';
import 'datatables';
import 'datatables-colreorder';
import 'drmonty-datatables-colvis';
import 'google-code-prettify/src/prettify';
import 'jquery-match-height';
import 'moment';
import 'moment-timezone';
import 'eonasdan-bootstrap-datetimepicker';
import 'patternfly/src/js/patternfly-settings';
import 'patternfly/src/js/patternfly-functions';
// import 'patternfly/src/js/patternfly.dataTables.pfEmpty';
// import 'patternfly/src/js/patternfly.dataTables.pfFilter';
// import 'patternfly/src/js/patternfly.dataTables.pfResize';
// import 'patternfly/src/js/patternfly.dataTables.pfSelect';
import 'angular-patternfly';
